//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditService.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuditService.Tests.Resources.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aus-sso-blocked-players-log.
        /// </summary>
        public static string BlockedPlayersLog {
            get {
                return ResourceManager.GetString("BlockedPlayersLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BlockedPlayersLogResponse {
            get {
                object obj = ResourceManager.GetObject("BlockedPlayersLogResponse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:9200.
        /// </summary>
        public static string ConnectionUrl {
            get {
                return ResourceManager.GetString("ConnectionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv.
        /// </summary>
        public static string CsvExtension {
            get {
                return ResourceManager.GetString("CsvExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aus-system-auditlog2.
        /// </summary>
        public static string DefaultIndex {
            get {
                return ResourceManager.GetString("DefaultIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElasticSearchAuditLogResponse {
            get {
                object obj = ResourceManager.GetObject("ElasticSearchAuditLogResponse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElasticSearchLossesLogResponse {
            get {
                object obj = ResourceManager.GetObject("ElasticSearchLossesLogResponse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElasticSearchVisitLogResponse {
            get {
                object obj = ResourceManager.GetObject("ElasticSearchVisitLogResponse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xlsx.
        /// </summary>
        public static string ExcelExtension {
            get {
                return ResourceManager.GetString("ExcelExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as-losseslog.
        /// </summary>
        public static string LossesLog {
            get {
                return ResourceManager.GetString("LossesLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aus-system-player-changes-log.
        /// </summary>
        public static string PlayerChangesLog {
            get {
                return ResourceManager.GetString("PlayerChangesLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeId1.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aus-sso-visit-log.
        /// </summary>
        public static string VisitLog {
            get {
                return ResourceManager.GetString("VisitLog", resourceCulture);
            }
        }
    }
}
